/*
 * Unless explicitly acquired and licensed from Licensor under another license, the contents of
 * this file are subject to the Reciprocal Public License ("RPL") Version 1.5, or subsequent
 * versions as allowed by the RPL, and You may not copy or use this file in either source code
 * or executable form, except in compliance with the terms and conditions of the RPL
 * 
 * All software distributed under the RPL is provided strictly on an "AS IS" basis, WITHOUT
 * WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED, AND LICENSOR HEREBY DISCLAIMS ALL SUCH
 * WARRANTIES, INCLUDING WITHOUT LIMITATION, ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
 * PARTICULAR PURPOSE, QUIET ENJOYMENT, OR NON-INFRINGEMENT. See the RPL for specific language
 * governing rights and limitations under the RPL.
 *
 * http://opensource.org/licenses/RPL-1.5
 *
 * Copyright 2012-2017 Open Justice Broker Consortium
 */
insert into Facility (FacilityID, FacilityDescription) values ('1', 'Adams County Detention Facility');
insert into Facility (FacilityID, FacilityDescription) values ('2', 'Adams County Justice Center');
insert into Facility (FacilityID, FacilityDescription) values ('3', 'Other Facility');
insert into Facility (FacilityID, FacilityDescription) values ('4', 'Unknown');
insert into Agency (AgencyID, AgencyDescription) values ('1', 'ADAMS COUNTY ANIMAL CONTROL');
insert into Agency (AgencyID, AgencyDescription) values ('2', 'ADAMS COUNTY COURTS');
insert into Agency (AgencyID, AgencyDescription) values ('3', 'ADAMS COUNTY SO');
insert into Agency (AgencyID, AgencyDescription) values ('4', 'ATTORNEY GENERAL');
insert into Agency (AgencyID, AgencyDescription) values ('5', 'AKRON PD');
insert into Agency (AgencyID, AgencyDescription) values ('6', 'ALAMOSA COUNTY SO');
insert into Agency (AgencyID, AgencyDescription) values ('7', 'ALAMOSA PD');
insert into Agency (AgencyID, AgencyDescription) values ('8', 'ANTONITO PD');
insert into Agency (AgencyID, AgencyDescription) values ('9', 'ARAPAHOE COUNTY SO');
insert into Agency (AgencyID, AgencyDescription) values ('10', 'ARCHULETA COUNTY SO');
insert into Agency (AgencyID, AgencyDescription) values ('11', 'UNITED STATES ARMY');
insert into Agency (AgencyID, AgencyDescription) values ('12', 'ARVADA PD');
insert into Agency (AgencyID, AgencyDescription) values ('13', 'ASPEN PD');
insert into Agency (AgencyID, AgencyDescription) values ('14', 'ALCOHOL TOBACCO FIREARMS');
insert into Agency (AgencyID, AgencyDescription) values ('15', 'AULT PD');
insert into Agency (AgencyID, AgencyDescription) values ('16', 'AURORA PD');
insert into Agency (AgencyID, AgencyDescription) values ('17', 'AVON PD');
insert into Agency (AgencyID, AgencyDescription) values ('18', 'BACA COUNTY SO');
insert into Agency (AgencyID, AgencyDescription) values ('19', 'BASALT PD');
insert into Agency (AgencyID, AgencyDescription) values ('20', 'BAYFIELD PD');
insert into Agency (AgencyID, AgencyDescription) values ('21', 'BOULDER COUNTY SO');
insert into Agency (AgencyID, AgencyDescription) values ('22', 'BENNETT PD');
insert into Agency (AgencyID, AgencyDescription) values ('23', 'BENT COUNTY SO');
insert into Agency (AgencyID, AgencyDescription) values ('24', 'BERTHOUD PD');
insert into Agency (AgencyID, AgencyDescription) values ('25', 'BLACKHAWK PD');
insert into Agency (AgencyID, AgencyDescription) values ('26', 'BURLINGTON NORTHERN RAILROAD');
insert into Agency (AgencyID, AgencyDescription) values ('27', 'BOULDER PD');
insert into Agency (AgencyID, AgencyDescription) values ('28', 'BOWMAR PD');
insert into Agency (AgencyID, AgencyDescription) values ('29', 'BRIGHTON PD');
insert into Agency (AgencyID, AgencyDescription) values ('30', 'BRECKENRIDGE PD');
insert into Agency (AgencyID, AgencyDescription) values ('31', 'BRIGHTON PD');
insert into Agency (AgencyID, AgencyDescription) values ('32', 'BROOMFIELD PD');
insert into Agency (AgencyID, AgencyDescription) values ('33', 'BRUSH PD');
insert into Agency (AgencyID, AgencyDescription) values ('34', 'BUENA VISTA PD');
insert into Agency (AgencyID, AgencyDescription) values ('35', 'BURLINGTON PD');
insert into Agency (AgencyID, AgencyDescription) values ('36', 'CALHAN PD');
insert into Agency (AgencyID, AgencyDescription) values ('37', 'CANON CITY PD');
insert into Agency (AgencyID, AgencyDescription) values ('38', 'CARBONDALE PD');
insert into Agency (AgencyID, AgencyDescription) values ('39', 'CASTLEROCK PD');
insert into Agency (AgencyID, AgencyDescription) values ('40', 'COLORADO BUREAU OF INVESTIGATION');
insert into Agency (AgencyID, AgencyDescription) values ('41', 'COMMERCE CITY PD');
insert into Agency (AgencyID, AgencyDescription) values ('42', 'COLORADO DEPT OF LABOR/EMPLOYMENT');
insert into Agency (AgencyID, AgencyDescription) values ('43', 'COLORADO DIVISION OF PARKS/REC');
insert into Agency (AgencyID, AgencyDescription) values ('44', 'COLORADO DEPARTMENT OF PUB SAFETY');
insert into Agency (AgencyID, AgencyDescription) values ('45', 'CEDARIDGE PD');
insert into Agency (AgencyID, AgencyDescription) values ('46', 'CENTRAL CITY PD');
insert into Agency (AgencyID, AgencyDescription) values ('47', 'CENTER PD');
insert into Agency (AgencyID, AgencyDescription) values ('48', 'CHAFFEE COUNTY SO');
insert into Agency (AgencyID, AgencyDescription) values ('49', 'CHERRY HILLS PD');
insert into Agency (AgencyID, AgencyDescription) values ('50', 'CHEYENNE COUNTY SO');
insert into Agency (AgencyID, AgencyDescription) values ('51', 'CLEAR CREEK SO');
insert into Agency (AgencyID, AgencyDescription) values ('52', 'COMMUNITY CORRECTIONS');
insert into Agency (AgencyID, AgencyDescription) values ('53', 'COLLBRAN PD');
insert into Agency (AgencyID, AgencyDescription) values ('54', 'COLUMBINE PD');
insert into Agency (AgencyID, AgencyDescription) values ('55', 'COMMERCE CITY PD');
insert into Agency (AgencyID, AgencyDescription) values ('56', 'CONEJOS COUNTY SO');
insert into Agency (AgencyID, AgencyDescription) values ('57', 'CORTEZ PD');
insert into Agency (AgencyID, AgencyDescription) values ('58', 'COSTILLA COUNTY SO');
insert into Agency (AgencyID, AgencyDescription) values ('59', 'COURTESY HOLD');
insert into Agency (AgencyID, AgencyDescription) values ('60', 'COMMUNITY PLACEMENT VIOLATION');
insert into Agency (AgencyID, AgencyDescription) values ('61', 'CRAIG PD');
insert into Agency (AgencyID, AgencyDescription) values ('62', 'CREEDE PD');
insert into Agency (AgencyID, AgencyDescription) values ('63', 'CRESTED BUTTE PD');
insert into Agency (AgencyID, AgencyDescription) values ('64', 'CRIPPLE CREEK PD');
insert into Agency (AgencyID, AgencyDescription) values ('65', 'CROWLEY COUNTY SO');
insert into Agency (AgencyID, AgencyDescription) values ('66', 'CRESTONE PD');
insert into Agency (AgencyID, AgencyDescription) values ('67', 'COLORADO STATE PATROL');
insert into Agency (AgencyID, AgencyDescription) values ('68', 'COLORADO SPRINGS PD');
insert into Agency (AgencyID, AgencyDescription) values ('69', 'CUSTER COUNTY SO');
insert into Agency (AgencyID, AgencyDescription) values ('70', 'DACONO PD');
insert into Agency (AgencyID, AgencyDescription) values ('71', 'DIVISION OF CRIMINAL JUSTICE');
insert into Agency (AgencyID, AgencyDescription) values ('72', 'DRUG ENFORCEMENT AGENCY');
insert into Agency (AgencyID, AgencyDescription) values ('73', 'DEBEQUE PD');
insert into Agency (AgencyID, AgencyDescription) values ('74', 'DEL NORTE PD');
insert into Agency (AgencyID, AgencyDescription) values ('75', 'DELTA COUNTY SO');
insert into Agency (AgencyID, AgencyDescription) values ('76', 'DENVER COUNTY SO');
insert into Agency (AgencyID, AgencyDescription) values ('77', 'DILLON PD');
insert into Agency (AgencyID, AgencyDescription) values ('78', 'DELTA PD');
insert into Agency (AgencyID, AgencyDescription) values ('79', 'DEPARTMENT OF CORRECTIONS');
insert into Agency (AgencyID, AgencyDescription) values ('80', 'DIVISION OF GAMING');
insert into Agency (AgencyID, AgencyDescription) values ('81', 'DOLORES COUNTY SO');
insert into Agency (AgencyID, AgencyDescription) values ('82', 'DEPARTMENT OF REVENUE/AUTO');
insert into Agency (AgencyID, AgencyDescription) values ('83', 'DOUGLAS COUNTY SO');
insert into Agency (AgencyID, AgencyDescription) values ('84', 'DOVE CREEK PD');
insert into Agency (AgencyID, AgencyDescription) values ('85', 'DIVISION OF WILDLIFE');
insert into Agency (AgencyID, AgencyDescription) values ('86', 'DENVER PD');
insert into Agency (AgencyID, AgencyDescription) values ('87', 'DURANGO PD');
insert into Agency (AgencyID, AgencyDescription) values ('88', 'DIVISION OF YOUTH SERVICES');
insert into Agency (AgencyID, AgencyDescription) values ('89', 'EADS PD');
insert into Agency (AgencyID, AgencyDescription) values ('90', 'EAGLE COUNTY SO');
insert into Agency (AgencyID, AgencyDescription) values ('91', 'EATON PD');
insert into Agency (AgencyID, AgencyDescription) values ('92', 'EDGEWATER PD');
insert into Agency (AgencyID, AgencyDescription) values ('93', 'EAGLE PD');
insert into Agency (AgencyID, AgencyDescription) values ('94', 'ELBERT COUNTY SO');
insert into Agency (AgencyID, AgencyDescription) values ('95', 'ELIZABETH PD');
insert into Agency (AgencyID, AgencyDescription) values ('96', 'EL PASO COUNTY SO');
insert into Agency (AgencyID, AgencyDescription) values ('97', 'EMPIRE PD');
insert into Agency (AgencyID, AgencyDescription) values ('98', 'ENGLEWOOD PD');
insert into Agency (AgencyID, AgencyDescription) values ('99', 'ERIE PD');
insert into Agency (AgencyID, AgencyDescription) values ('100', 'ESTES PARK PD');
insert into Agency (AgencyID, AgencyDescription) values ('101', 'EVANS PD');
insert into Agency (AgencyID, AgencyDescription) values ('102', 'EXTRADITION');
insert into Agency (AgencyID, AgencyDescription) values ('103', 'FAIRPLAY PD');
insert into Agency (AgencyID, AgencyDescription) values ('104', 'FEDERAL BUREAU OF INVESTIGATION');
insert into Agency (AgencyID, AgencyDescription) values ('105', 'FEDERAL HEIGHTS PD');
insert into Agency (AgencyID, AgencyDescription) values ('106', 'FEDERAL HEIGHTS PD');
insert into Agency (AgencyID, AgencyDescription) values ('107', 'FIRESTONE PD');
insert into Agency (AgencyID, AgencyDescription) values ('108', 'FITZSIMMONS MILITARY POLICE');
insert into Agency (AgencyID, AgencyDescription) values ('109', 'FLAGLER PD');
insert into Agency (AgencyID, AgencyDescription) values ('110', 'FLEMING PD');
insert into Agency (AgencyID, AgencyDescription) values ('111', 'FLORENCE PD');
insert into Agency (AgencyID, AgencyDescription) values ('112', 'FORT COLLINS PD');
insert into Agency (AgencyID, AgencyDescription) values ('113', 'FOUNTAIN PD');
insert into Agency (AgencyID, AgencyDescription) values ('114', 'FOWLER PD');
insert into Agency (AgencyID, AgencyDescription) values ('115', 'FREDERICK PD');
insert into Agency (AgencyID, AgencyDescription) values ('116', 'FREMONT COUNTY SO');
insert into Agency (AgencyID, AgencyDescription) values ('117', 'FRISCO PD');
insert into Agency (AgencyID, AgencyDescription) values ('118', 'FRUITA PD');
insert into Agency (AgencyID, AgencyDescription) values ('119', 'FORT LOGAN MENTAL HEALTH');
insert into Agency (AgencyID, AgencyDescription) values ('120', 'FORT LUPTON PD');
insert into Agency (AgencyID, AgencyDescription) values ('121', 'FORT MORGAN PD');
insert into Agency (AgencyID, AgencyDescription) values ('122', 'GARFIELD COUNTY SO');
insert into Agency (AgencyID, AgencyDescription) values ('123', 'GEORGETOWN PD');
insert into Agency (AgencyID, AgencyDescription) values ('124', 'GILCREST PD');
insert into Agency (AgencyID, AgencyDescription) values ('125', 'GILPIN COUNTY SO');
insert into Agency (AgencyID, AgencyDescription) values ('126', 'GLENDALE PD');
insert into Agency (AgencyID, AgencyDescription) values ('127', 'GLENWOOD PD');
insert into Agency (AgencyID, AgencyDescription) values ('128', 'GOLDEN PD');
insert into Agency (AgencyID, AgencyDescription) values ('129', 'GRAND COUNTY SO');
insert into Agency (AgencyID, AgencyDescription) values ('130', 'GRANADA PD');
insert into Agency (AgencyID, AgencyDescription) values ('131', 'GREELEY PD');
insert into Agency (AgencyID, AgencyDescription) values ('132', 'GRAND JUNCTION PD');
insert into Agency (AgencyID, AgencyDescription) values ('133', 'GREEN MOUNTAIN PD');
insert into Agency (AgencyID, AgencyDescription) values ('134', 'GREENWOOD VILLAGE PD');
insert into Agency (AgencyID, AgencyDescription) values ('135', 'GUNNISON COUNTY SO');
insert into Agency (AgencyID, AgencyDescription) values ('136', 'GUNNISON PD');
insert into Agency (AgencyID, AgencyDescription) values ('137', 'GYPSUM PD');
insert into Agency (AgencyID, AgencyDescription) values ('138', 'HAXTUN PD');
insert into Agency (AgencyID, AgencyDescription) values ('139', 'HAYDEN PD');
insert into Agency (AgencyID, AgencyDescription) values ('140', 'HINSDALE COUNTY SO');
insert into Agency (AgencyID, AgencyDescription) values ('141', 'HOLLY PD');
insert into Agency (AgencyID, AgencyDescription) values ('142', 'HOLYOKE PD');
insert into Agency (AgencyID, AgencyDescription) values ('143', 'HOTCHKISS PD');
insert into Agency (AgencyID, AgencyDescription) values ('144', 'HUERFANO COUNTY SO');
insert into Agency (AgencyID, AgencyDescription) values ('145', 'HUGO PD');
insert into Agency (AgencyID, AgencyDescription) values ('146', 'IMMIGRATION CUSTOMS ENFORCEMENT');
insert into Agency (AgencyID, AgencyDescription) values ('147', 'IDAHO SPRINGS PD');
insert into Agency (AgencyID, AgencyDescription) values ('148', 'IGNACIO PD');
insert into Agency (AgencyID, AgencyDescription) values ('149', 'INTERPAC AGREEMENT');
insert into Agency (AgencyID, AgencyDescription) values ('150', 'JACKSON COUNTY SO');
insert into Agency (AgencyID, AgencyDescription) values ('151', 'JEFFERSON COUNTY SO');
insert into Agency (AgencyID, AgencyDescription) values ('152', 'JOHNSTOWN PD');
insert into Agency (AgencyID, AgencyDescription) values ('153', 'JULESBURG PD');
insert into Agency (AgencyID, AgencyDescription) values ('154', 'KIOWA COUNTY SO');
insert into Agency (AgencyID, AgencyDescription) values ('155', 'KIT CARSON COUNTY SO');
insert into Agency (AgencyID, AgencyDescription) values ('156', 'KREMMLING PD');
insert into Agency (AgencyID, AgencyDescription) values ('157', 'LAKE COUNTY SO');
insert into Agency (AgencyID, AgencyDescription) values ('158', 'LAFAYETTE PD');
insert into Agency (AgencyID, AgencyDescription) values ('159', 'LA JARA PD');
insert into Agency (AgencyID, AgencyDescription) values ('160', 'LA JUNTA PD');
insert into Agency (AgencyID, AgencyDescription) values ('161', 'LAKEWOOD PD');
insert into Agency (AgencyID, AgencyDescription) values ('162', 'LAMAR PD');
insert into Agency (AgencyID, AgencyDescription) values ('163', 'LAPLATA COUNTY SO');
insert into Agency (AgencyID, AgencyDescription) values ('164', 'LARIMER COUNTY SO');
insert into Agency (AgencyID, AgencyDescription) values ('165', 'LAS ANIMAS COUNTY SO');
insert into Agency (AgencyID, AgencyDescription) values ('166', 'LASALLE PD');
insert into Agency (AgencyID, AgencyDescription) values ('167', 'LAS ANIMAS PD');
insert into Agency (AgencyID, AgencyDescription) values ('168', 'LAVETA PD');
insert into Agency (AgencyID, AgencyDescription) values ('169', 'LEADVILLE PD');
insert into Agency (AgencyID, AgencyDescription) values ('170', 'LIMON PD');
insert into Agency (AgencyID, AgencyDescription) values ('171', 'LINCOLN COUNTY SO');
insert into Agency (AgencyID, AgencyDescription) values ('172', 'LITTLETON PD');
insert into Agency (AgencyID, AgencyDescription) values ('173', 'LOG LANE VILLAGE PD');
insert into Agency (AgencyID, AgencyDescription) values ('174', 'LOCHBUIE PD');
insert into Agency (AgencyID, AgencyDescription) values ('175', 'LOGAN COUNTY SO');
insert into Agency (AgencyID, AgencyDescription) values ('176', 'LONETREE PD');
insert into Agency (AgencyID, AgencyDescription) values ('177', 'LONGMONT PD');
insert into Agency (AgencyID, AgencyDescription) values ('178', 'LOUISVILLE PD');
insert into Agency (AgencyID, AgencyDescription) values ('179', 'LOVELAND PD');
insert into Agency (AgencyID, AgencyDescription) values ('180', 'LYONS PD');
insert into Agency (AgencyID, AgencyDescription) values ('181', 'MANASASSA PD');
insert into Agency (AgencyID, AgencyDescription) values ('182', 'MANCOS PD');
insert into Agency (AgencyID, AgencyDescription) values ('183', 'MANITOU PD');
insert into Agency (AgencyID, AgencyDescription) values ('184', 'MANZANOLA PD');
insert into Agency (AgencyID, AgencyDescription) values ('185', 'MEEKER PD');
insert into Agency (AgencyID, AgencyDescription) values ('186', 'MESA COUNTY SO');
insert into Agency (AgencyID, AgencyDescription) values ('187', 'MILLIKEN PD');
insert into Agency (AgencyID, AgencyDescription) values ('188', 'MINERAL COUNTY SO');
insert into Agency (AgencyID, AgencyDescription) values ('189', 'MINTURN PD');
insert into Agency (AgencyID, AgencyDescription) values ('190', 'MITTIMUS (SENTENCED)');
insert into Agency (AgencyID, AgencyDescription) values ('191', 'MONTROSE PD');
insert into Agency (AgencyID, AgencyDescription) values ('192', 'MONTEZUMA COUNTY SO');
insert into Agency (AgencyID, AgencyDescription) values ('193', 'MONTE VISTA PD');
insert into Agency (AgencyID, AgencyDescription) values ('194', 'MOFFAT COUNTY SO');
insert into Agency (AgencyID, AgencyDescription) values ('195', 'MONTROSE COUNTY SO');
insert into Agency (AgencyID, AgencyDescription) values ('196', 'MONUMENT PD');
insert into Agency (AgencyID, AgencyDescription) values ('197', 'MORGAN COUNTY SO');
insert into Agency (AgencyID, AgencyDescription) values ('198', 'MORRISON PD');
insert into Agency (AgencyID, AgencyDescription) values ('199', 'MONT CRESTED BUTTE PD');
insert into Agency (AgencyID, AgencyDescription) values ('200', 'METRO TASK FORCE');
insert into Agency (AgencyID, AgencyDescription) values ('201', 'MOUNTAIN VIEW PD');
insert into Agency (AgencyID, AgencyDescription) values ('202', 'NATURITA PD');
insert into Agency (AgencyID, AgencyDescription) values ('203', 'UNITED STATES NAVY');
insert into Agency (AgencyID, AgencyDescription) values ('204', 'NEDERLAND PD');
insert into Agency (AgencyID, AgencyDescription) values ('205', 'NEW CASTLE PD');
insert into Agency (AgencyID, AgencyDescription) values ('206', 'NORTH METRO TASK FORCE');
insert into Agency (AgencyID, AgencyDescription) values ('207', 'NORTHGLENN PD');
insert into Agency (AgencyID, AgencyDescription) values ('208', 'NORTHGLENN PD');
insert into Agency (AgencyID, AgencyDescription) values ('209', 'NORWOOD PD');
insert into Agency (AgencyID, AgencyDescription) values ('210', 'NUCLA PD');
insert into Agency (AgencyID, AgencyDescription) values ('211', 'OAK CREEKE PD');
insert into Agency (AgencyID, AgencyDescription) values ('212', 'ORDWAY PD');
insert into Agency (AgencyID, AgencyDescription) values ('213', 'OTERO COUNTY SO');
insert into Agency (AgencyID, AgencyDescription) values ('214', 'OTIS PD');
insert into Agency (AgencyID, AgencyDescription) values ('215', 'OURAY COUNTY SO');
insert into Agency (AgencyID, AgencyDescription) values ('216', 'OURAY PD');
insert into Agency (AgencyID, AgencyDescription) values ('217', 'OUT OF STATE AGENCY');
insert into Agency (AgencyID, AgencyDescription) values ('218', 'OVID PD');
insert into Agency (AgencyID, AgencyDescription) values ('219', 'PAGOSA PD');
insert into Agency (AgencyID, AgencyDescription) values ('220', 'PALISADE PD');
insert into Agency (AgencyID, AgencyDescription) values ('221', 'PALMER PD');
insert into Agency (AgencyID, AgencyDescription) values ('222', 'PAONIA PD');
insert into Agency (AgencyID, AgencyDescription) values ('223', 'PARACHUTE PD');
insert into Agency (AgencyID, AgencyDescription) values ('224', 'PARK COUNTY SO');
insert into Agency (AgencyID, AgencyDescription) values ('225', 'PAROLE');
insert into Agency (AgencyID, AgencyDescription) values ('226', 'PHILLIPS COUNTY SO');
insert into Agency (AgencyID, AgencyDescription) values ('227', 'PITKIN COUNTY SO');
insert into Agency (AgencyID, AgencyDescription) values ('228', 'PLATTEVILLE PD');
insert into Agency (AgencyID, AgencyDescription) values ('229', 'PORT OF ENTRY');
insert into Agency (AgencyID, AgencyDescription) values ('230', 'PARKER PD');
insert into Agency (AgencyID, AgencyDescription) values ('231', 'PROBATION');
insert into Agency (AgencyID, AgencyDescription) values ('232', 'PROWERS COUNTY SO');
insert into Agency (AgencyID, AgencyDescription) values ('233', 'PUEBLO COUNTY SO');
insert into Agency (AgencyID, AgencyDescription) values ('234', 'PUEBLO PD');
insert into Agency (AgencyID, AgencyDescription) values ('235', 'RANGELY PD');
insert into Agency (AgencyID, AgencyDescription) values ('236', 'RED CLIFF PD');
insert into Agency (AgencyID, AgencyDescription) values ('237', 'RICO');
insert into Agency (AgencyID, AgencyDescription) values ('238', 'RIDGEWAY PD');
insert into Agency (AgencyID, AgencyDescription) values ('239', 'RIFLE PD');
insert into Agency (AgencyID, AgencyDescription) values ('240', 'RIO BLANCO COUNTY SO');
insert into Agency (AgencyID, AgencyDescription) values ('241', 'RIO GRANDE COUNTY SO');
insert into Agency (AgencyID, AgencyDescription) values ('242', 'ROCKY FORD PD');
insert into Agency (AgencyID, AgencyDescription) values ('243', 'ROUTT COUNTY SO');
insert into Agency (AgencyID, AgencyDescription) values ('244', 'SAGUACHE PD');
insert into Agency (AgencyID, AgencyDescription) values ('245', 'SAGUACHE COUNTY SO');
insert into Agency (AgencyID, AgencyDescription) values ('246', 'SALIDA PD');
insert into Agency (AgencyID, AgencyDescription) values ('247', 'SANFORD PD');
insert into Agency (AgencyID, AgencyDescription) values ('248', 'SAN JUAN COUNTY SO');
insert into Agency (AgencyID, AgencyDescription) values ('249', 'SAN MIGUEL COUNTY SO');
insert into Agency (AgencyID, AgencyDescription) values ('250', 'SEDGEWICK COUNTY SO');
insert into Agency (AgencyID, AgencyDescription) values ('251', 'SEDGEWICK PD');
insert into Agency (AgencyID, AgencyDescription) values ('252', 'SHERIDAN PD');
insert into Agency (AgencyID, AgencyDescription) values ('253', 'SILT PD');
insert into Agency (AgencyID, AgencyDescription) values ('254', 'SILVERTHORNE PD');
insert into Agency (AgencyID, AgencyDescription) values ('255', 'SNOWMASS PD');
insert into Agency (AgencyID, AgencyDescription) values ('256', 'SPRINGFIELD PD');
insert into Agency (AgencyID, AgencyDescription) values ('257', 'SECRET SERVICE');
insert into Agency (AgencyID, AgencyDescription) values ('258', 'STEAMBOAT SPRINTS PD');
insert into Agency (AgencyID, AgencyDescription) values ('259', 'STERLING PD');
insert into Agency (AgencyID, AgencyDescription) values ('260', 'STRATTON PD');
insert into Agency (AgencyID, AgencyDescription) values ('261', 'SUMMIT COUNTY SO');
insert into Agency (AgencyID, AgencyDescription) values ('262', 'TELLER COUNTY SO');
insert into Agency (AgencyID, AgencyDescription) values ('263', 'TELLURIDE PD');
insert into Agency (AgencyID, AgencyDescription) values ('264', 'THORNTON PD');
insert into Agency (AgencyID, AgencyDescription) values ('265', 'UNIVERSITY OF COLORADO HEALTH SERVICES');
insert into Agency (AgencyID, AgencyDescription) values ('266', 'UNITED STATES AIR FORCE');
insert into Agency (AgencyID, AgencyDescription) values ('267', 'UNITED STATES MARSHALL');
insert into Agency (AgencyID, AgencyDescription) values ('268', 'UNITED STATES MARINE CORP');
insert into Agency (AgencyID, AgencyDescription) values ('269', 'UNITED STATES MINT');
insert into Agency (AgencyID, AgencyDescription) values ('270', 'VAIL PD');
insert into Agency (AgencyID, AgencyDescription) values ('271', 'VICTOR PD');
insert into Agency (AgencyID, AgencyDescription) values ('272', 'WALDEN PD');
insert into Agency (AgencyID, AgencyDescription) values ('273', 'WALSH PD');
insert into Agency (AgencyID, AgencyDescription) values ('274', 'WALSENBURG PD');
insert into Agency (AgencyID, AgencyDescription) values ('275', 'WASHINGTON COUNTY SO');
insert into Agency (AgencyID, AgencyDescription) values ('276', 'WELD COUNTY SO');
insert into Agency (AgencyID, AgencyDescription) values ('277', 'WESTCLIFFE PD');
insert into Agency (AgencyID, AgencyDescription) values ('278', 'WESTMINSTER PD');
insert into Agency (AgencyID, AgencyDescription) values ('279', 'WHEAT RIDGE PD');
insert into Agency (AgencyID, AgencyDescription) values ('280', 'WIGGINS PD');
insert into Agency (AgencyID, AgencyDescription) values ('281', 'WILEY PD');
insert into Agency (AgencyID, AgencyDescription) values ('282', 'WINDSOR PD');
insert into Agency (AgencyID, AgencyDescription) values ('283', 'WOODMOOR');
insert into Agency (AgencyID, AgencyDescription) values ('284', 'WOODLAND PARK PD');
insert into Agency (AgencyID, AgencyDescription) values ('285', 'WRAY PD');
insert into Agency (AgencyID, AgencyDescription) values ('286', 'WRIT (COURT APPEARANCE)');
insert into Agency (AgencyID, AgencyDescription) values ('287', 'YAMPA PD');
insert into Agency (AgencyID, AgencyDescription) values ('288', 'YUMA COUNTY SO');
insert into Agency (AgencyID, AgencyDescription) values ('289', 'YUMA PD');
insert into Agency (AgencyID, AgencyDescription) values ('290', 'Unknown');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('1', 'A Module');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('2', 'Booking');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('3', 'B Module');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('4', 'C Module');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('5', 'Courthouse');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('6', 'Colorado State Hospital');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('7', 'D Module');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('8', 'E Module');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('9', 'Escaped');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('10', 'F Module Floor 1');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('11', 'F Module Floor 2');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('12', 'Furlough');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('13', 'Hospital');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('14', 'Infirmary');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('15', 'Interpacts');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('16', 'Pre Release 1');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('17', 'Pre Release 2');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('18', 'WRIT');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('19', 'Unknown');
insert into BondStatusType (BondStatusTypeID, BondStatusTypeDescription) values ('1', 'Posted Bond');
insert into BondStatusType (BondStatusTypeID, BondStatusTypeDescription) values ('2', 'Return to Other Jurisdiction');
insert into BondStatusType (BondStatusTypeID, BondStatusTypeDescription) values ('3', 'Released Order of Court');
insert into BondStatusType (BondStatusTypeID, BondStatusTypeDescription) values ('4', 'Served Time Release');
insert into BondStatusType (BondStatusTypeID, BondStatusTypeDescription) values ('5', 'Sentenced');
insert into BondStatusType (BondStatusTypeID, BondStatusTypeDescription) values ('6', 'Active');
insert into BondStatusType (BondStatusTypeID, BondStatusTypeDescription) values ('7', 'No Charges');
insert into BondStatusType (BondStatusTypeID, BondStatusTypeDescription) values ('8', 'Parole Release');
insert into BondStatusType (BondStatusTypeID, BondStatusTypeDescription) values ('9', 'WTRN');
insert into BondStatusType (BondStatusTypeID, BondStatusTypeDescription) values ('10', 'Watch Commander Release');
insert into BondStatusType (BondStatusTypeID, BondStatusTypeDescription) values ('11', 'Investigator Release');
insert into BondStatusType (BondStatusTypeID, BondStatusTypeDescription) values ('12', 'CTS');
insert into BondStatusType (BondStatusTypeID, BondStatusTypeDescription) values ('13', 'Vacated Charges');
insert into BondStatusType (BondStatusTypeID, BondStatusTypeDescription) values ('14', 'No Probable Cause');
insert into BondStatusType (BondStatusTypeID, BondStatusTypeDescription) values ('15', 'FCR');
insert into BondStatusType (BondStatusTypeID, BondStatusTypeDescription) values ('16', 'Deceased');
insert into BondStatusType (BondStatusTypeID, BondStatusTypeDescription) values ('17', 'Combined Charges');
insert into BondStatusType (BondStatusTypeID, BondStatusTypeDescription) values ('18', 'I');
insert into BondStatusType (BondStatusTypeID, BondStatusTypeDescription) values ('19', 'OTHR');
insert into BondStatusType (BondStatusTypeID, BondStatusTypeDescription) values ('20', 'RTRJ');
insert into BondStatusType (BondStatusTypeID, BondStatusTypeDescription) values ('21', 'CASH');
insert into BondStatusType (BondStatusTypeID, BondStatusTypeDescription) values ('22', 'PEND');
insert into BondStatusType (BondStatusTypeID, BondStatusTypeDescription) values ('23', 'PR');
insert into BondStatusType (BondStatusTypeID, BondStatusTypeDescription) values ('24', 'SUR');
insert into BondType (BondTypeID, BondTypeDescription) values ('1', 'CASH/SURETY');
insert into BondType (BondTypeID, BondTypeDescription) values ('2', 'SURETY');
insert into BondType (BondTypeID, BondTypeDescription) values ('3', 'SERVED TIME RELEASE');
insert into BondType (BondTypeID, BondTypeDescription) values ('4', 'ROC');
insert into BondType (BondTypeID, BondTypeDescription) values ('5', 'SENTENCED');
insert into BondType (BondTypeID, BondTypeDescription) values ('6', 'NO BOND');
insert into BondType (BondTypeID, BondTypeDescription) values ('7', 'CASH BOND');
insert into BondType (BondTypeID, BondTypeDescription) values ('8', 'RTOJ');
insert into BondType (BondTypeID, BondTypeDescription) values ('9', 'PR BOND');
insert into BondType (BondTypeID, BondTypeDescription) values ('10', 'CASH/SURETY/PROPERTY');
insert into BondType (BondTypeID, BondTypeDescription) values ('11', 'PR BOND - SUPERVISED RELEASE');
insert into BondType (BondTypeID, BondTypeDescription) values ('12', 'CASH/SURETY SRP');
insert into BondType (BondTypeID, BondTypeDescription) values ('13', 'SPLIT BOND');
insert into BondType (BondTypeID, BondTypeDescription) values ('14', 'WTRN');
insert into BondType (BondTypeID, BondTypeDescription) values ('15', 'WATCH COMMANDER RELEASE');
insert into BondType (BondTypeID, BondTypeDescription) values ('16', 'FINES AND COST RELEASE');
insert into BondType (BondTypeID, BondTypeDescription) values ('17', 'SUPERVISED RELEASE PROGRAM');
insert into BondType (BondTypeID, BondTypeDescription) values ('18', 'OTHER');
insert into BondType (BondTypeID, BondTypeDescription) values ('19', 'NOCH');
insert into BondType (BondTypeID, BondTypeDescription) values ('20', 'PARR');
insert into BondType (BondTypeID, BondTypeDescription) values ('21', 'CTS');
insert into BondType (BondTypeID, BondTypeDescription) values ('22', 'CASH/SURETY/PROPERTY-SRP');
insert into BondType (BondTypeID, BondTypeDescription) values ('23', 'INTR');
insert into BondType (BondTypeID, BondTypeDescription) values ('24', 'PROPERTY BOND');
insert into BondType (BondTypeID, BondTypeDescription) values ('25', 'CASH FINE ONLY');
insert into BondType (BondTypeID, BondTypeDescription) values ('26', 'SUSR');
insert into BondType (BondTypeID, BondTypeDescription) values ('27', 'INVS');
insert into BondType (BondTypeID, BondTypeDescription) values ('28', 'PR BOND - SRP CO-SIGN');
insert into BondType (BondTypeID, BondTypeDescription) values ('29', 'SUR');
insert into BondType (BondTypeID, BondTypeDescription) values ('30', 'WRTN');
insert into BondType (BondTypeID, BondTypeDescription) values ('31', 'CASH/SURETY/PROPERTY CO-SIGNED');
insert into BondType (BondTypeID, BondTypeDescription) values ('32', 'NOPC');
insert into BondType (BondTypeID, BondTypeDescription) values ('33', 'SRSP');
insert into BondType (BondTypeID, BondTypeDescription) values ('34', 'SUSP');
insert into BondType (BondTypeID, BondTypeDescription) values ('35', '0');
insert into BondType (BondTypeID, BondTypeDescription) values ('36', 'CSRJ');
insert into BondType (BondTypeID, BondTypeDescription) values ('37', 'CVLJ');
insert into BondType (BondTypeID, BondTypeDescription) values ('38', 'DECE');
insert into BondType (BondTypeID, BondTypeDescription) values ('39', 'NOBJ');
insert into BondType (BondTypeID, BondTypeDescription) values ('40', 'NOCG');
insert into BondType (BondTypeID, BondTypeDescription) values ('41', 'NODH');
insert into BondType (BondTypeID, BondTypeDescription) values ('42', 'OC');
insert into BondType (BondTypeID, BondTypeDescription) values ('43', 'POST');
insert into BondType (BondTypeID, BondTypeDescription) values ('44', 'ROJ');
insert into BondType (BondTypeID, BondTypeDescription) values ('45', 'ROTJ');
insert into BondType (BondTypeID, BondTypeDescription) values ('46', 'RRTJ');
insert into BondType (BondTypeID, BondTypeDescription) values ('47', 'RTJO');
insert into BondType (BondTypeID, BondTypeDescription) values ('48', 'RTO');
insert into BondType (BondTypeID, BondTypeDescription) values ('49', 'SPL');
insert into BondType (BondTypeID, BondTypeDescription) values ('50', 'SUMM');
insert into BondType (BondTypeID, BondTypeDescription) values ('51', 'VAC');
insert into BondType (BondTypeID, BondTypeDescription) values ('52', 'WRN');
insert into BondType (BondTypeID, BondTypeDescription) values ('53', 'WTR');
insert into BondType (BondTypeID, BondTypeDescription) values ('54', 'WTRQ');
insert into BondType (BondTypeID, BondTypeDescription) values ('55', 'X');
insert into BondType (BondTypeID, BondTypeDescription) values ('56', 'CREDIT CARD');
insert into BondType (BondTypeID, BondTypeDescription) values ('57', 'PR BOND COSIGNED');
insert into ChargeClassType (ChargeClassTypeID, ChargeClassTypeDescription) values ('1', 'Felony');
insert into ChargeClassType (ChargeClassTypeID, ChargeClassTypeDescription) values ('2', 'Misdemeanor');
insert into ChargeClassType (ChargeClassTypeID, ChargeClassTypeDescription) values ('3', 'Petty');
insert into ChargeClassType (ChargeClassTypeID, ChargeClassTypeDescription) values ('4', 'Traffic');
insert into ChargeClassType (ChargeClassTypeID, ChargeClassTypeDescription) values ('5', 'Unknown');
insert into DomicileStatusType (DomicileStatusTypeID, DomicileStatusTypeDescription) values ('1', 'Unknown');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('1', 'ADAMS COUNTY COURTS');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('2', 'DEPARTMENT OF CORRECTIONS');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('3', 'AURORA PD');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('4', 'ARVADA PD');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('5', 'JEFFERSON COUNTY SO');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('6', 'PAROLE');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('7', 'COMMERCE CITY PD');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('8', 'COMMUNITY CORRECTIONS');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('9', 'WHEAT RIDGE PD');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('10', 'BOULDER COUNTY SO');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('11', 'DENVER COUNTY SO');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('12', 'ARAPAHOE COUNTY SO');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('13', 'WESTMINSTER PD');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('14', 'PUEBLO COUNTY SO');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('15', 'FEDERAL HEIGHTS PD');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('16', 'EL PASO COUNTY SO');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('17', 'DOUGLAS COUNTY SO');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('18', 'WELD COUNTY SO');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('19', 'LOGAN COUNTY SO');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('20', 'LAKEWOOD PD');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('21', 'THORNTON PD');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('22', 'BRIGHTON PD');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('23', 'BROOMFIELD PD');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('24', 'GILPIN COUNTY SO');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('25', 'LONETREE PD');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('26', 'UNITED STATES MARSHALL');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('27', 'EAGLE COUNTY SO');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('28', 'DIVISION OF YOUTH SERVICES');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('29', 'GREELEY PD');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('30', 'EXTRADITION');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('31', 'COSTILLA COUNTY SO');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('32', 'COMMUNITY PLACEMENT VIOLATION');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('33', 'BOULDER PD');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('34', 'MESA COUNTY SO');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('35', 'EDGEWATER PD');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('36', 'LARIMER COUNTY SO');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('37', 'KIT CARSON COUNTY SO');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('38', 'NORTHGLENN PD');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('39', 'DENVER PD');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('40', 'MOFFAT COUNTY SO');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('41', 'WASHINGTON COUNTY SO');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('42', 'FORT LUPTON PD');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('43', 'CLEAR CREEK SO');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('44', 'BACA COUNTY SO');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('45', 'ALCOHOL TOBACCO FIREARMS');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('46', 'ENGLEWOOD PD');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('47', 'SHERIDAN PD');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('48', 'GOLDEN PD');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('49', 'PROWERS COUNTY SO');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('50', 'HUERFANO COUNTY SO');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('51', 'MORGAN COUNTY SO');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('52', 'LONGMONT PD');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('53', 'ELBERT COUNTY SO');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('54', 'LITTLETON PD');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('55', 'SUMMIT COUNTY SO');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('56', 'MOUNTAIN VIEW PD');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('57', 'BLACKHAWK PD');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('58', 'GLENDALE PD');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('59', 'FORT COLLINS PD');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('60', 'GARFIELD COUNTY SO');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('61', 'FORT MORGAN PD');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('62', 'LAKE COUNTY SO');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('63', 'GREENWOOD VILLAGE PD');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('64', 'DIVISION OF CRIMINAL JUSTICE');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('65', 'GUNNISON COUNTY SO');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('66', 'ALAMOSA COUNTY SO');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('67', 'LAPLATA COUNTY SO');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('68', 'CROWLEY COUNTY SO');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('69', 'CHEYENNE COUNTY SO');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('70', 'WIGGINS PD');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('71', 'ADAMS COUNTY ANIMAL CONTROL');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('72', 'CHAFFEE COUNTY SO');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('73', 'FREMONT COUNTY SO');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('74', 'TELLER COUNTY SO');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('75', 'COLUMBINE PD');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('76', 'GRAND COUNTY SO');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('77', 'LOCHBUIE PD');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('78', 'DELTA COUNTY SO');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('79', 'RIO GRANDE COUNTY SO');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('80', 'DACONO PD');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('81', 'ARCHULETA COUNTY SO');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('82', 'ROUTT COUNTY SO');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('83', 'PARK COUNTY SO');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('84', 'LINCOLN COUNTY SO');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('85', 'IMMIGRATION CUSTOMS ENFORCEMENT');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('86', 'UNITED STATES ARMY');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('87', 'YUMA COUNTY SO');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('88', 'SAGUACHE COUNTY SO');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('89', 'LAS ANIMAS COUNTY SO');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('90', 'ERIE PD');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('91', 'LAFAYETTE PD');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('92', 'RIO BLANCO COUNTY SO');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('93', 'MONTROSE COUNTY SO');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('94', 'CUSTER COUNTY SO');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('95', 'BENNETT PD');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('96', 'CASTLEROCK PD');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('97', 'ESTES PARK PD');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('98', 'ALAMOSA PD');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('99', 'BRECKENRIDGE PD');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('100', 'COLORADO BUREAU OF INVESTIGATION');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('101', 'BENT COUNTY SO');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('102', 'OTERO COUNTY SO');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('103', 'SEDGEWICK COUNTY SO');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('104', 'CENTRAL CITY PD');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('105', 'LOUISVILLE PD');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('106', 'OUT OF STATE AGENCY');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('107', 'BERTHOUD PD');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('108', 'WALSENBURG PD');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('109', 'WRIT (COURT APPEARANCE)');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('110', 'SILVERTHORNE PD');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('111', 'RIFLE PD');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('112', 'CHERRY HILLS PD');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('113', 'KIOWA COUNTY SO');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('114', 'MITTIMUS (SENTENCED)');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('115', 'GRAND JUNCTION PD');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('116', 'AULT PD');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('117', 'ATTORNEY GENERAL');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('118', 'FREDERICK PD');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('119', 'CONEJOS COUNTY SO');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('120', 'COLORADO STATE PATROL');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('121', 'PARKER PD');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('122', 'FLORENCE PD');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('123', 'FEDERAL BUREAU OF INVESTIGATION');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('124', 'LOVELAND PD');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('125', 'MONTEZUMA COUNTY SO');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('126', 'MINERAL COUNTY SO');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('127', 'PITKIN COUNTY SO');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('128', 'GLENWOOD PD');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('129', 'CANON CITY PD');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('130', 'NEDERLAND PD');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('131', 'PHILLIPS COUNTY SO');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('132', 'EAGLE PD');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('133', 'FORT LOGAN MENTAL HEALTH');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('134', 'DURANGO PD');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('135', 'KREMMLING PD');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('136', 'AVON PD');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('137', 'JOHNSTOWN PD');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('138', 'FIRESTONE PD');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('139', 'BURLINGTON PD');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('140', 'UNITED STATES NAVY');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('99999', 'Unknown');
insert into LanguageType (LanguageTypeID, LanguageTypeDescription) values ('1', 'English');
insert into LanguageType (LanguageTypeID, LanguageTypeDescription) values ('2', 'Mexican');
insert into LanguageType (LanguageTypeID, LanguageTypeDescription) values ('3', 'Unknown');
insert into MedicaidStatusType (MedicaidStatusTypeID, MedicaidStatusTypeDescription) values ('1', 'Unknown');
insert into MilitaryServiceStatusType (MilitaryServiceStatusTypeID, MilitaryServiceStatusTypeDescription) values ('1', 'Active');
insert into MilitaryServiceStatusType (MilitaryServiceStatusTypeID, MilitaryServiceStatusTypeDescription) values ('2', 'AWOL');
insert into MilitaryServiceStatusType (MilitaryServiceStatusTypeID, MilitaryServiceStatusTypeDescription) values ('3', 'Dishonorable Discharge');
insert into MilitaryServiceStatusType (MilitaryServiceStatusTypeID, MilitaryServiceStatusTypeDescription) values ('4', 'Honorable Discharge');
insert into MilitaryServiceStatusType (MilitaryServiceStatusTypeID, MilitaryServiceStatusTypeDescription) values ('5', 'Medical Discharge');
insert into MilitaryServiceStatusType (MilitaryServiceStatusTypeID, MilitaryServiceStatusTypeDescription) values ('6', 'Non Active');
insert into MilitaryServiceStatusType (MilitaryServiceStatusTypeID, MilitaryServiceStatusTypeDescription) values ('7', 'Retired');
insert into MilitaryServiceStatusType (MilitaryServiceStatusTypeID, MilitaryServiceStatusTypeDescription) values ('8', 'Unknown');
insert into PersonEthnicityType (PersonEthnicityTypeID, PersonEthnicityTypeDescription) values ('1', 'Hispanic');
insert into PersonEthnicityType (PersonEthnicityTypeID, PersonEthnicityTypeDescription) values ('2', 'Non-Hispanic');
insert into PersonEthnicityType (PersonEthnicityTypeID, PersonEthnicityTypeDescription) values ('3', 'Unknown');
insert into PersonRaceType (PersonRaceTypeID, PersonRaceTypeDescription) values ('1', 'Asian');
insert into PersonRaceType (PersonRaceTypeID, PersonRaceTypeDescription) values ('2', 'Black');
insert into PersonRaceType (PersonRaceTypeID, PersonRaceTypeDescription) values ('3', 'American Indian / Alaska Native');
insert into PersonRaceType (PersonRaceTypeID, PersonRaceTypeDescription) values ('4', 'Native Hawaiian or Pacific Islander');
insert into PersonRaceType (PersonRaceTypeID, PersonRaceTypeDescription) values ('5', 'Unknown');
insert into PersonRaceType (PersonRaceTypeID, PersonRaceTypeDescription) values ('6', 'White');
insert into PersonSexType (PersonSexTypeID, PersonSexTypeDescription) values ('1', 'Male');
insert into PersonSexType (PersonSexTypeID, PersonSexTypeDescription) values ('2', 'Female');
insert into PersonSexType (PersonSexTypeID, PersonSexTypeDescription) values ('3', 'Unknown');
insert into ProgramEligibilityType (ProgramEligibilityTypeID, ProgramEligibilityTypeDescription) values ('1', 'Unknown');
insert into SexOffenderStatusType (SexOffenderStatusTypeID, SexOffenderStatusTypeDescription) values ('1', 'Not Registered');
insert into SexOffenderStatusType (SexOffenderStatusTypeID, SexOffenderStatusTypeDescription) values ('2', 'Registered');
insert into SexOffenderStatusType (SexOffenderStatusTypeID, SexOffenderStatusTypeDescription) values ('3', 'Unknown');
insert into TreatmentAdmissionReasonType (TreatmentAdmissionReasonTypeID, TreatmentAdmissionReasonTypeDescription) values ('1', 'Unknown');
insert into TreatmentStatusType (TreatmentStatusTypeID, TreatmentStatusTypeDescription) values ('1', 'Unknown');
insert into WorkReleaseStatusType (WorkReleaseStatusTypeID, WorkReleaseStatusTypeDescription) values ('1', 'Not Assigned');
insert into WorkReleaseStatusType (WorkReleaseStatusTypeID, WorkReleaseStatusTypeDescription) values ('2', 'Assigned');
insert into WorkReleaseStatusType (WorkReleaseStatusTypeID, WorkReleaseStatusTypeDescription) values ('3', 'Unknown');
