/*
 * Unless explicitly acquired and licensed from Licensor under another license, the contents of
 * this file are subject to the Reciprocal Public License ("RPL") Version 1.5, or subsequent
 * versions as allowed by the RPL, and You may not copy or use this file in either source code
 * or executable form, except in compliance with the terms and conditions of the RPL
 * 
 * All software distributed under the RPL is provided strictly on an "AS IS" basis, WITHOUT
 * WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED, AND LICENSOR HEREBY DISCLAIMS ALL SUCH
 * WARRANTIES, INCLUDING WITHOUT LIMITATION, ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
 * PARTICULAR PURPOSE, QUIET ENJOYMENT, OR NON-INFRINGEMENT. See the RPL for specific language
 * governing rights and limitations under the RPL.
 *
 * http://opensource.org/licenses/RPL-1.5
 *
 * Copyright 2012-2017 Open Justice Broker Consortium
 */
insert into Facility (FacilityID, FacilityDescription) values ('1', 'Pima County Adult Detention Complex');
insert into Agency (AgencyID, AgencyDescription) values ('1', 'Department of Transportation');
insert into Agency (AgencyID, AgencyDescription) values ('2', 'Pima County Adult Probation');
insert into Agency (AgencyID, AgencyDescription) values ('3', 'Drug Enforcement');
insert into Agency (AgencyID, AgencyDescription) values ('4', 'Department of Public Safety');
insert into Agency (AgencyID, AgencyDescription) values ('5', 'EMS: Pima Co. Sheriff Dept.');
insert into Agency (AgencyID, AgencyDescription) values ('6', 'Fed Bureau of Investigation');
insert into Agency (AgencyID, AgencyDescription) values ('7', 'FIRE: Pima Co. Sheriff Dept.');
insert into Agency (AgencyID, AgencyDescription) values ('8', 'Immigration & Naturalization');
insert into Agency (AgencyID, AgencyDescription) values ('9', 'Marana Police Department');
insert into Agency (AgencyID, AgencyDescription) values ('10', 'Miscellaneous Calls');
insert into Agency (AgencyID, AgencyDescription) values ('11', 'Oro Valley Misc. Type Call');
insert into Agency (AgencyID, AgencyDescription) values ('12', 'Oro Valley Police Department');
insert into Agency (AgencyID, AgencyDescription) values ('13', 'National Park Service');
insert into Agency (AgencyID, AgencyDescription) values ('14', 'Pima Community College Police');
insert into Agency (AgencyID, AgencyDescription) values ('15', 'Pima County Parks & Recreation');
insert into Agency (AgencyID, AgencyDescription) values ('16', 'Pima County Sheriff Dept.');
insert into Agency (AgencyID, AgencyDescription) values ('17', 'Pinal County Sheriff Dept');
insert into Agency (AgencyID, AgencyDescription) values ('18', 'Union Pacific Railroad');
insert into Agency (AgencyID, AgencyDescription) values ('19', 'South Tucson Police Dept');
insert into Agency (AgencyID, AgencyDescription) values ('20', 'Tucson Airport Authority PD');
insert into Agency (AgencyID, AgencyDescription) values ('21', 'Tucson Airport Fire');
insert into Agency (AgencyID, AgencyDescription) values ('22', 'Sells Police Department');
insert into Agency (AgencyID, AgencyDescription) values ('23', 'Tucson Police Department');
insert into Agency (AgencyID, AgencyDescription) values ('24', 'Univ of Arizona Campus Police');
insert into Agency (AgencyID, AgencyDescription) values ('25', 'Counter Narcotics Alliance');
insert into Agency (AgencyID, AgencyDescription) values ('26', 'Pascua Yaqui Police Department');
insert into Agency (AgencyID, AgencyDescription) values ('27', 'Sahuarita Police Department');
insert into Agency (AgencyID, AgencyDescription) values ('28', 'Arizona Capitol Police');
insert into Agency (AgencyID, AgencyDescription) values ('29', 'NSIS: Pima Co. Sheriff Dept.');
insert into Agency (AgencyID, AgencyDescription) values ('30', 'Pima Animal Control');
insert into Agency (AgencyID, AgencyDescription) values ('31', 'Bureau Alcohol/Tobacco/Firearm');
insert into Agency (AgencyID, AgencyDescription) values ('32', 'Pima County Attorney');
insert into Agency (AgencyID, AgencyDescription) values ('33', 'Pascua Yaqui Tribe Prosecutors');
insert into Agency (AgencyID, AgencyDescription) values ('34', 'Marana Prosecutor Office');
insert into Agency (AgencyID, AgencyDescription) values ('35', 'Sahuarita Prosecutor Office');
insert into Agency (AgencyID, AgencyDescription) values ('36', 'Office of the Attorney General');
insert into Agency (AgencyID, AgencyDescription) values ('37', 'Bureau of Land Management');
insert into Agency (AgencyID, AgencyDescription) values ('38', 'Immigration and Customs Enforc');
insert into Agency (AgencyID, AgencyDescription) values ('39', 'Department of Corrections');
insert into Agency (AgencyID, AgencyDescription) values ('40', 'US Forest Service');
insert into Agency (AgencyID, AgencyDescription) values ('41', 'US Marshall');
insert into Agency (AgencyID, AgencyDescription) values ('42', 'US Postal Service');
insert into Agency (AgencyID, AgencyDescription) values ('43', 'Arizona Game and Fish');
insert into Agency (AgencyID, AgencyDescription) values ('44', 'US Border Patrol');
insert into Agency (AgencyID, AgencyDescription) values ('45', 'City of Tucson Probation');
insert into Agency (AgencyID, AgencyDescription) values ('46', 'Institutional Health');
insert into Agency (AgencyID, AgencyDescription) values ('47', 'AZ Dept of Juvenile Correction');
insert into Agency (AgencyID, AgencyDescription) values ('48', 'Unknown');
insert into AssessmentCategoryType (AssessmentCategoryTypeID, AssessmentCategoryTypeDescription) values ('1', 'General Mental Health');
insert into AssessmentCategoryType (AssessmentCategoryTypeID, AssessmentCategoryTypeDescription) values ('2', 'Substance Abuse');
insert into AssessmentCategoryType (AssessmentCategoryTypeID, AssessmentCategoryTypeDescription) values ('3', 'Danger To Self');
insert into AssessmentCategoryType (AssessmentCategoryTypeID, AssessmentCategoryTypeDescription) values ('4', 'Danger To Others');
insert into AssessmentCategoryType (AssessmentCategoryTypeID, AssessmentCategoryTypeDescription) values ('5', 'Gravely Disabled');
insert into AssessmentCategoryType (AssessmentCategoryTypeID, AssessmentCategoryTypeDescription) values ('6', 'Persistently and Acutely Disabled');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('1', 'AJO IN TRANSIT');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('2', 'AJO UNIT A');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('3', 'AJO UNIT B');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('4', 'AJO UNIT C');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('5', 'ASH');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('6', 'AWOL');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('7', 'CRT,DOWNTOWN COURT');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('8', 'CRT,EAST VIDEO COURT');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('9', 'CRT,JUVENILE COURT');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('10', 'CRT,TOWER VIDEO COURT');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('11', 'DOC');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('12', 'EAST INFIRMARY');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('13', 'EAST INTAKE');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('14', 'EAST POD 1P');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('15', 'EAST POD 1Q');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('16', 'EAST POD 1R');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('17', 'EAST POD 1S');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('18', 'EAST POD 2P');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('19', 'EAST POD 2Q');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('20', 'EAST POD 2R');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('21', 'EAST POD 2S');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('22', 'EAST PROPERTY');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('23', 'ESCAPE');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('24', 'FCI');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('25', 'HDEM');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('26', 'IDENTIFICATION UNIT-UNIT 5');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('27', 'INFIRMARY-UNIT 7');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('28', 'JUDICIAL SECURITY');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('29', 'JUDICIAL, 7-HOLDING');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('30', 'JUDICIAL, B-LEVEL');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('31', 'JUDICIAL, JUSTICE COURT MID LEVL');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('32', 'JUDICIAL, JUVENILE COURT HOLDING');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('33', 'LAUNDRY');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('34', 'LAW LIBRARY');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('35', 'MEDICAL-UNIT 6');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('36', 'MISSION INTAKE');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('37', 'MISSION POD 5');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('38', 'MISSION POD 6E');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('39', 'MSF FURLOUGH, SCHOOL');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('40', 'MSF FURLOUGH, TREATMENT');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('41', 'MSF LOADING CREW');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('42', 'MSF WORK RELEASE');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('43', 'MSF WRK CRW, COMMISSARY (FEMALES)');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('44', 'MSF WRK CRW, DOWNTOWN (MALES)');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('45', 'MSF WRK CRW, FLOOR CRE (MALES)');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('46', 'MSF WRK CRW, INTAKE PORTER');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('47', 'MSF WRK CRW, KITCHEN AM (UNIT 10)');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('48', 'MSF WRK CRW, KITCHEN MID-DAY (UNIT 10)');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('49', 'MSF WRK CRW, KITCHEN PM (UNIT 10)');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('50', 'MSF WRK CRW, PACC (FEMALES)');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('51', 'OCAG');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('52', 'OOAG');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('53', 'PCJC');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('54', 'POAG');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('55', 'PORTER, TOWER 1A');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('56', 'PORTER, TOWER 1S');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('57', 'PORTER, TOWER 2P');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('58', 'PORTER, TOWER 4D');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('59', 'PRGM,CAPE PROGRAM');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('60', 'PRGM,EAST PROGRAM RM 1602');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('61', 'PRGM,EAST PROGRAM RM 2606');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('62', 'PRGM,EAST PROGRAM RM 2609');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('63', 'PRGM,GED PROGRAM RM');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('64', 'PRGM,MSF PROGRAM RM');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('65', 'PRGM,TOWER MULTI-PURPOSE RM');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('66', 'PRGM,WEST 1EF CAPE CLASSROOM');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('67', 'PRGM,WEST 1H PROGAM RM');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('68', 'PRGM,WEST HOUSING UNIT DAY RM');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('69', 'PRGM,WEST PROGRAM RM');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('70', 'PYPD Holding');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('71', 'RETURN TO COMPENTENCY');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('72', 'SECURITY SERVICES');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('73', 'SUPPLY');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('74', 'TEMP OUT-COURT ORDERED');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('75', 'TOWER POD 1A');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('76', 'TOWER POD 1D');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('77', 'TOWER POD 2A');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('78', 'TOWER POD 2B');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('79', 'TOWER POD 2C');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('80', 'TOWER POD 2D');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('81', 'TOWER POD 3A');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('82', 'TOWER POD 3B');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('83', 'TOWER POD 3C');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('84', 'TOWER POD 3D');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('85', 'TOWER POD 4A');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('86', 'TOWER POD 4B');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('87', 'TOWER POD 4C');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('88', 'TOWER POD 4D');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('89', 'TRANSPORT');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('90', 'VIS,PROFESSIONAL VISITATION-UNIT 9');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('91', 'VIS,WEST VISITATION');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('92', 'VISITATION');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('93', 'WEEKENDER RELEASE');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('94', 'WEEKENDER RETURN');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('95', 'WEST POD 1EF');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('96', 'WEST POD 1G');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('97', 'WEST POD 1H');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('98', 'WEST POD 1J');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('99', 'WEST POD 1K');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('100', 'WEST POD 1L');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('101', 'WEST POD 2FG');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('102', 'YARDS, UNIT 11 (A,B,C,D,E)');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('103', 'YARDS, UNIT 11 (ADJACENT)');
insert into SupervisionUnitType (SupervisionUnitTypeID, SupervisionUnitTypeDescription) values ('104', 'Unknown');
insert into BondStatusType (BondStatusTypeID, BondStatusTypeDescription) values ('1', 'Release/Own Recognizance');
insert into BondStatusType (BondStatusTypeID, BondStatusTypeDescription) values ('2', 'Court Ordered');
insert into BondStatusType (BondStatusTypeID, BondStatusTypeDescription) values ('3', 'Sentenced');
insert into BondStatusType (BondStatusTypeID, BondStatusTypeDescription) values ('4', 'Bond Posted');
insert into BondStatusType (BondStatusTypeID, BondStatusTypeDescription) values ('5', 'Administrative Clearance');
insert into BondStatusType (BondStatusTypeID, BondStatusTypeDescription) values ('6', 'Unknown');
insert into BondType (BondTypeID, BondTypeDescription) values ('1', 'Unknown');
insert into BondType (BondTypeID, BondTypeDescription) values ('2', 'Cash Only');
insert into BondType (BondTypeID, BondTypeDescription) values ('3', 'Cash or Secured');
insert into BondType (BondTypeID, BondTypeDescription) values ('4', 'Hold Without Bond');
insert into BondType (BondTypeID, BondTypeDescription) values ('5', 'Secured');
insert into BondType (BondTypeID, BondTypeDescription) values ('6', 'Combination');
insert into ChargeClassType (ChargeClassTypeID, ChargeClassTypeDescription) values ('1', 'Class 2 felony');
insert into ChargeClassType (ChargeClassTypeID, ChargeClassTypeDescription) values ('2', 'Class 1 felony');
insert into ChargeClassType (ChargeClassTypeID, ChargeClassTypeDescription) values ('3', 'Class 3 felony');
insert into ChargeClassType (ChargeClassTypeID, ChargeClassTypeDescription) values ('4', 'Class 4 felony');
insert into ChargeClassType (ChargeClassTypeID, ChargeClassTypeDescription) values ('5', 'Class 5 felony');
insert into ChargeClassType (ChargeClassTypeID, ChargeClassTypeDescription) values ('6', 'Class 6 felony');
insert into ChargeClassType (ChargeClassTypeID, ChargeClassTypeDescription) values ('7', 'Class 1 Misdemeanor');
insert into ChargeClassType (ChargeClassTypeID, ChargeClassTypeDescription) values ('8', 'Class 2 Misdemeanor');
insert into ChargeClassType (ChargeClassTypeID, ChargeClassTypeDescription) values ('9', 'Class 3 Misdemeanor');
insert into ChargeClassType (ChargeClassTypeID, ChargeClassTypeDescription) values ('10', 'Petty Offense');
insert into ChargeClassType (ChargeClassTypeID, ChargeClassTypeDescription) values ('11', 'FELONY, CLASS UNKNOWN');
insert into ChargeClassType (ChargeClassTypeID, ChargeClassTypeDescription) values ('12', 'MISDEMEANOR, CLASS UNKNOWN');
insert into ChargeClassType (ChargeClassTypeID, ChargeClassTypeDescription) values ('13', 'CHILD SUPPORT');
insert into ChargeClassType (ChargeClassTypeID, ChargeClassTypeDescription) values ('14', 'Open end - Felony or Misd.');
insert into ChargeClassType (ChargeClassTypeID, ChargeClassTypeDescription) values ('15', 'NOT UNDERLYING OFFENSE');
insert into ChargeClassType (ChargeClassTypeID, ChargeClassTypeDescription) values ('16', 'Material Witness');
insert into ChargeClassType (ChargeClassTypeID, ChargeClassTypeDescription) values ('17', 'Tribal');
insert into ChargeClassType (ChargeClassTypeID, ChargeClassTypeDescription) values ('18', 'Unknown');
insert into DomicileStatusType (DomicileStatusTypeID, DomicileStatusTypeDescription) values ('1', 'Not Homeless');
insert into DomicileStatusType (DomicileStatusTypeID, DomicileStatusTypeDescription) values ('2', 'Homeless');
insert into DomicileStatusType (DomicileStatusTypeID, DomicileStatusTypeDescription) values ('3', 'Unknown');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('1', 'TUCSON CITY COURT');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('2', 'SOUTH TUCSON CITY COURT');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('3', 'JUSTICE COURT #1');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('4', 'JUSTICE COURT #3');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('5', 'JUSTICE COURT #7');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('6', 'ORO VALLEY MAGISTRATE COURT');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('7', 'JUSTICE COURT');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('8', 'SUPERIOR COURT');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('9', 'MARANA MAGISTRATE COURT');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('10', 'SAHUARITA MUNICIPAL COURT');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('11', 'Justice Court Other County');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('12', 'AZ Dept of Corrections');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('13', 'United States Border Patrol');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('14', 'Immigration & Customs Enforcem');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('15', 'Dept of Institutional Health');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('16', 'Federal Agencies,USM Billing');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('17', 'SUP CRT,AZ STATE COST RECOVERY');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('18', 'AZ State - PV,HOLDS,OTH');
insert into JurisdictionType (JurisdictionTypeID, JurisdictionTypeDescription) values ('19', 'Unknown');
insert into LanguageType (LanguageTypeID, LanguageTypeDescription) values ('1', 'Lisp');
insert into LanguageType (LanguageTypeID, LanguageTypeDescription) values ('2', 'Stutters');
insert into LanguageType (LanguageTypeID, LanguageTypeDescription) values ('3', 'High Pitched');
insert into LanguageType (LanguageTypeID, LanguageTypeDescription) values ('4', 'Deep Voice');
insert into LanguageType (LanguageTypeID, LanguageTypeDescription) values ('5', 'Slurred');
insert into LanguageType (LanguageTypeID, LanguageTypeDescription) values ('6', 'Mute/None');
insert into LanguageType (LanguageTypeID, LanguageTypeDescription) values ('7', 'Accented');
insert into LanguageType (LanguageTypeID, LanguageTypeDescription) values ('8', 'Unintelligible');
insert into LanguageType (LanguageTypeID, LanguageTypeDescription) values ('9', 'Spanish Speaker');
insert into LanguageType (LanguageTypeID, LanguageTypeDescription) values ('10', 'German Speaker');
insert into LanguageType (LanguageTypeID, LanguageTypeDescription) values ('11', 'Japanese Speaker');
insert into LanguageType (LanguageTypeID, LanguageTypeDescription) values ('12', 'Chinese Speaker');
insert into LanguageType (LanguageTypeID, LanguageTypeDescription) values ('13', 'Sign Language');
insert into LanguageType (LanguageTypeID, LanguageTypeDescription) values ('14', 'Other Language');
insert into LanguageType (LanguageTypeID, LanguageTypeDescription) values ('15', 'Vietnamese Speaker');
insert into LanguageType (LanguageTypeID, LanguageTypeDescription) values ('16', 'Korean Speaker');
insert into LanguageType (LanguageTypeID, LanguageTypeDescription) values ('17', 'Thai Speaker');
insert into LanguageType (LanguageTypeID, LanguageTypeDescription) values ('18', 'French Speaker');
insert into LanguageType (LanguageTypeID, LanguageTypeDescription) values ('19', 'Swedish Speaker');
insert into LanguageType (LanguageTypeID, LanguageTypeDescription) values ('20', 'Russian Speaker');
insert into LanguageType (LanguageTypeID, LanguageTypeDescription) values ('21', 'Apache Speaker');
insert into LanguageType (LanguageTypeID, LanguageTypeDescription) values ('22', 'Bosnian Speaker');
insert into LanguageType (LanguageTypeID, LanguageTypeDescription) values ('23', 'Cantonese Speaker');
insert into LanguageType (LanguageTypeID, LanguageTypeDescription) values ('24', 'Croation Speaker');
insert into LanguageType (LanguageTypeID, LanguageTypeDescription) values ('25', 'Chech Speaker');
insert into LanguageType (LanguageTypeID, LanguageTypeDescription) values ('26', 'Dinka/Sudan Speaker');
insert into LanguageType (LanguageTypeID, LanguageTypeDescription) values ('27', 'Ethiopian Speaker');
insert into LanguageType (LanguageTypeID, LanguageTypeDescription) values ('28', 'Farsi Speaker');
insert into LanguageType (LanguageTypeID, LanguageTypeDescription) values ('29', 'Hindu Speaker');
insert into LanguageType (LanguageTypeID, LanguageTypeDescription) values ('30', 'Italian Speaker');
insert into LanguageType (LanguageTypeID, LanguageTypeDescription) values ('31', 'Arabic Speaker');
insert into LanguageType (LanguageTypeID, LanguageTypeDescription) values ('32', 'Filipino Speaker');
insert into LanguageType (LanguageTypeID, LanguageTypeDescription) values ('33', 'Mandarin Speaker');
insert into LanguageType (LanguageTypeID, LanguageTypeDescription) values ('34', 'Navajo Speaker');
insert into LanguageType (LanguageTypeID, LanguageTypeDescription) values ('35', 'Polish Speaker');
insert into LanguageType (LanguageTypeID, LanguageTypeDescription) values ('36', 'Romanian Speaker');
insert into LanguageType (LanguageTypeID, LanguageTypeDescription) values ('37', 'Taglog Speaker');
insert into LanguageType (LanguageTypeID, LanguageTypeDescription) values ('38', 'Tohono O\''Odham Speaker');
insert into LanguageType (LanguageTypeID, LanguageTypeDescription) values ('39', 'Tonga Speaker');
insert into LanguageType (LanguageTypeID, LanguageTypeDescription) values ('40', 'Ukrainian Speaker');
insert into LanguageType (LanguageTypeID, LanguageTypeDescription) values ('41', 'English Speaker');
insert into LanguageType (LanguageTypeID, LanguageTypeDescription) values ('42', 'Swahili Speaker');
insert into LanguageType (LanguageTypeID, LanguageTypeDescription) values ('43', 'Somali Speaker');
insert into LanguageType (LanguageTypeID, LanguageTypeDescription) values ('44', 'Hungarian Speaker');
insert into LanguageType (LanguageTypeID, LanguageTypeDescription) values ('45', 'Nepalese');
insert into LanguageType (LanguageTypeID, LanguageTypeDescription) values ('46', 'Unknown');
insert into MedicaidStatusType (MedicaidStatusTypeID, MedicaidStatusTypeDescription) values ('1', 'Not Eligible');
insert into MedicaidStatusType (MedicaidStatusTypeID, MedicaidStatusTypeDescription) values ('2', 'Eligible');
insert into MedicaidStatusType (MedicaidStatusTypeID, MedicaidStatusTypeDescription) values ('3', 'Unknown');
insert into PersonEthnicityType (PersonEthnicityTypeID, PersonEthnicityTypeDescription) values ('1', 'Latino');
insert into PersonEthnicityType (PersonEthnicityTypeID, PersonEthnicityTypeDescription) values ('2', 'Non-Latino');
insert into PersonEthnicityType (PersonEthnicityTypeID, PersonEthnicityTypeDescription) values ('3', 'Unknown');
insert into PersonRaceType (PersonRaceTypeID, PersonRaceTypeDescription) values ('1', 'Hispanic');
insert into PersonRaceType (PersonRaceTypeID, PersonRaceTypeDescription) values ('2', 'Native Amer., Aleutes, Eskimos');
insert into PersonRaceType (PersonRaceTypeID, PersonRaceTypeDescription) values ('3', 'Black / African American');
insert into PersonRaceType (PersonRaceTypeID, PersonRaceTypeDescription) values ('4', 'Asian or Pacific Islander');
insert into PersonRaceType (PersonRaceTypeID, PersonRaceTypeDescription) values ('5', 'Caucasian');
insert into PersonRaceType (PersonRaceTypeID, PersonRaceTypeDescription) values ('6', 'Unknown');
insert into PersonSexType (PersonSexTypeID, PersonSexTypeDescription) values ('1', 'Male');
insert into PersonSexType (PersonSexTypeID, PersonSexTypeDescription) values ('2', 'Female');
insert into PersonSexType (PersonSexTypeID, PersonSexTypeDescription) values ('3', 'Unknown');
insert into ProgramEligibilityType (ProgramEligibilityTypeID, ProgramEligibilityTypeDescription) values ('1', 'None');
insert into ProgramEligibilityType (ProgramEligibilityTypeID, ProgramEligibilityTypeDescription) values ('2', 'Veteran Services');
insert into ProgramEligibilityType (ProgramEligibilityTypeID, ProgramEligibilityTypeDescription) values ('3', 'Unknown');
insert into TreatmentAdmissionReasonType (TreatmentAdmissionReasonTypeID, TreatmentAdmissionReasonTypeDescription) values ('1', 'Court-Ordered Treatment');
insert into TreatmentAdmissionReasonType (TreatmentAdmissionReasonTypeID, TreatmentAdmissionReasonTypeDescription) values ('2', 'Other');
insert into TreatmentStatusType (TreatmentStatusTypeID, TreatmentStatusTypeDescription) values ('1', 'Active');
insert into TreatmentStatusType (TreatmentStatusTypeID, TreatmentStatusTypeDescription) values ('2', 'Inactive');
insert into TreatmentStatusType (TreatmentStatusTypeID, TreatmentStatusTypeDescription) values ('3', 'Crisis');
