# Open Justice Broker configuration file for the Static Mock Adapter
spring.main.allow-bean-definition-overriding=true

genericMockAdapter.dbAuditLog=false

################################################ 
####  Person Search Request Flow Endpoints  ####
################################################

# Note: Person Search Request is the flow that obtains the results of a person search

# Person Search Request Endpoints - Adapters (Mocks or hosted at partner agencies - called by Intermediary)
genericMockAdapter.personSearchRequestEndpoint=/adapter/PersonSearchRequestService

# Person Search Response Handler Endpoints - OJB Intermediary (callback, called by Adapters)
genericMockAdapter.personSearchResultsHandlerEndpoint=https://localhost:8443/OJB/intermediary/PersonSearchResultsService

#Used to write requests to file system
genericMockAdapter.personSearchRequest.mockFileEndpoint=/tmp/ojb/adapter/mock/personSearchRequest/

#Indicates whether to lock web service messages
genericMockAdapter.personSearchRequestMockCxflogging=true

################################################
	Custody Search Endpoints
################################################

# Custody Search Request Endpoints - Adapters (Mocks or hosted at partner agencies - called by Intermediary)
genericMockAdapter.custodySearchRequestEndpoint=/adapter/CustodySearchRequestService

# Custody Search Response Handler Endpoints - OJB Intermediary (callback, called by Adapters)
genericMockAdapter.custodySearchResultsHandlerEndpoint=https://localhost:8443/OJB/intermediary/CustodySearchResultsService

genericMockAdapter.custodySearchRequestMockCxflogging=true

################################################
	Court Case Search Endpoints
################################################

# Court Case Search Request Endpoints - Adapters (Mocks or hosted at partner agencies - called by Intermediary)
genericMockAdapter.courtCaseSearchRequestEndpoint=/adapter/CourtCaseSearchRequestService

# Court Case Search Response Handler Endpoints - OJB Intermediary (callback, called by Adapters)
genericMockAdapter.courtCaseSearchResultsHandlerEndpoint=https://localhost:8443/OJB/intermediary/CourtCaseSearchResultsService

genericMockAdapter.courtCaseSearchRequestMockCxflogging=true

################################################# 
####  Firearm Search Request Flow Endpoints  ####
#################################################

# Firearm Search Request Endpoints - Adapters (Mocks or hosted at partner agencies - called by Intermediary)
genericMockAdapter.firearmSearchRequestEndpoint=/adapter/FirearmSearchRequestService

# Firearm Search Response Handler Endpoints - OJB Intermediary (callback, called by Adapters)
genericMockAdapter.firearmSearchResultsHandlerEndpoint=https://localhost:8443/OJB/intermediary/FirearmSearchResultsService

#Used to write requests to file system
genericMockAdapter.firearmSearchRequest.mockFileEndpoint=/tmp/ojb/adapter/mock/firearmSearchRequest/

#Indicates whether to lock web service messages
genericMockAdapter.firearmSearchRequestMockCxflogging=true

################################################# 
####  Vehicle Search Request Flow Endpoints  ####
#################################################

# Vehicle Search Request Endpoints - Adapters (Mocks or hosted at partner agencies - called by Intermediary)
genericMockAdapter.vehicleSearchRequestEndpoint=/adapter/VehicleSearchRequestService

# Vehicle Search Response Handler Endpoints - OJB Intermediary (callback, called by Adapters)
genericMockAdapter.vehicleSearchResultsHandlerEndpoint=https://localhost:8443/OJB/intermediary/VehicleSearchResultsService

#Used to write requests to file system
genericMockAdapter.vehicleSearchRequest.mockFileEndpoint=/tmp/ojb/adapter/mock/vehicleSearchRequest/

#Indicates whether to lock web service messages
genericMockAdapter.vehicleSearchRequestMockCxflogging=true

################################################## 
####  Incident Search Request Flow Endpoints  ####
##################################################

# Incident Search Request Endpoints - Adapters (Mocks or hosted at partner agencies - called by Intermediary)
genericMockAdapter.incidentSearchRequestEndpoint=/adapter/IncidentSearchRequestService

# Incident Search Response Handler Endpoints - OJB Intermediary (callback, called by Adapters)
genericMockAdapter.incidentSearchResultsHandlerEndpoint=https://localhost:8443/OJB/intermediary/IncidentSearchResultsService

#Used to write requests to file system
genericMockAdapter.incidentSearchRequest.mockFileEndpoint=/tmp/ojb/adapter/mock/incidentSearchRequest/

#Indicates whether to lock web service messages
genericMockAdapter.incidentSearchRequestMockCxflogging=true

########################################### 
####  Wildlife License Flow Endpoints  ####
###########################################
# Wildlife License Request Endpoints - Adapters (Mocks or hosted at partner agencies - called by Intermediary)
genericMockAdapter.wildlifeLicenseRequestEndpoint=/adapter/WildlifeLicenseRequestService

# Wildlife License Response Handler Endpoints - OJB Intermediary (callback, called by Adapters)
genericMockAdapter.wildlifeLicenseResultsHandlerEndpoint=https://localhost:8443/OJB/intermediary/PersonQueryWildlifeLicenseResultsService

#Used to write requests to file system
genericMockAdapter.wildlifeLicenseRequest.mockFileEndpoint=/tmp/ojb/adapter/mock/wildlifeLicenseRequest/

#Indicates whether to lock web service messages
genericMockAdapter.wildlifeLicenseRequestMockCxflogging=true

##########################################
####  Query Flow Endpoints  ####
##########################################

# Note: Query Request is the flow that obtains the detail for one selected record

# Query Request Endpoints - Adapters (Mocks or hosted at partner agencies - called by Intermediary)
genericMockAdapter.personQueryCriminalHistoryEndpoint=/adapter/PersonQueryServiceCriminalHistoryService
genericMockAdapter.personQueryWarrantsEndpoint=/adapter/PersonQueryServiceWarrantsService
genericMockAdapter.personQueryIncidentReportEndpoint=/adapter/PersonQueryServiceIncidentReportService
genericMockAdapter.personQueryFirearmEndpoint=/adapter/PersonQueryServiceFirearmService
genericMockAdapter.casePlanHistoryRequestServiceEndpoint=/adapter/CasePlanHistoryRequestService
genericMockAdapter.hearingHistoryRequestServiceEndpoint=/adapter/HearingHistoryRequestService
genericMockAdapter.intakeHistoryRequestServiceEndpoint=/adapter/IntakeHistoryRequestService
genericMockAdapter.offenseHistoryRequestServiceEndpoint=/adapter/OffenseHistoryRequestService
genericMockAdapter.placementHistoryRequestServiceEndpoint=/adapter/PlacementHistoryRequestService
genericMockAdapter.referralHistoryRequestServiceEndpoint=/adapter/ReferralHistoryRequestService
genericMockAdapter.custodyQueryEndpoint=/adapter/CustodyQueryService
genericMockAdapter.courtCaseQueryEndpoint=/adapter/CourtCaseQueryService
genericMockAdapter.vehicleCrashQueryEndpoint=/adapter/PersonQueryVehicleCrashService
genericMockAdapter.firearmsPurchaseProhibitionQueryEndpoint=/adapter/FirearmsPurchaseProhibitionQueryRequestService


# Query Response Handler Endpoints - OJB Intermediary (callback, called by Adapters)
genericMockAdapter.personQueryResultsHandlerCriminalHistoryEndpoint=https://localhost:8443/OJB/intermediary/PersonQueryResultsHandlerServiceCriminalHistoryService
genericMockAdapter.personQueryResultsHandlerWarrantsHandlerEndpoint=https://localhost:8443/OJB/intermediary/PersonQueryResultsHandlerServiceWarrantsService
genericMockAdapter.personQueryResultsHandlerIncidentReportResultsEndpoint=https://localhost:8443/OJB/intermediary/IncidentReportResultsService
genericMockAdapter.personQueryResultsHandlerFirearmEndpoint=https://localhost:8443/OJB/intermediary/FirearmRegistrationQueryResultsHandlerService
genericMockAdapter.casePlanHistoryResultsServiceEndpoint=https://localhost:8443/OJB/intermediary/CasePlanHistoryResultsHandlerService
genericMockAdapter.hearingHistoryResultsServiceEndpoint=https://localhost:8443/OJB/intermediary/HearingHistoryResultsHandlerService
genericMockAdapter.intakeHistoryResultsServiceEndpoint=https://localhost:8443/OJB/intermediary/IntakeHistoryResultsHandlerService
genericMockAdapter.offenseHistoryResultsServiceEndpoint=https://localhost:8443/OJB/intermediary/OffenseHistoryResultsHandlerService
genericMockAdapter.placementHistoryResultsServiceEndpoint=https://localhost:8443/OJB/intermediary/PlacementHistoryResultsHandlerService
genericMockAdapter.referralHistoryResultsServiceEndpoint=https://localhost:8443/OJB/intermediary/ReferralHistoryResultsHandlerService
genericMockAdapter.custodyQueryResultsHandlerEndpoint=https://localhost:8443/OJB/intermediary/CustodyQueryResultsHandlerService
genericMockAdapter.courtCaseQueryResultsHandlerEndpoint=https://localhost:8443/OJB/intermediary/CourtCaseQueryResultsHandlerService
genericMockAdapter.vehicleCrashQueryResultsHandlerEndpoint=https://localhost:8443/OJB/intermediary/PersonQueryVehicleCrashResultsService
genericMockAdapter.firearmsPurchaseProhibitionQueryResultsHandlerEndpoint=https://localhost:8443/OJB/intermediary/FirearmsPurchaseProhibitionQueryResultsHandlerService

#Used to write requests to file system
genericMockAdapter.personQuery.mockFileEndpoint=/tmp/ojb/adapter/mock/personQuery/

#Indicates whether to log web service messages
genericMockAdapter.personQueryMockCxflogging=true
genericMockAdapter.CustodyQueryMockCxflogging=true
genericMockAdapter.courtCaseQueryMockCxflogging=true

#Keystore used to sign messages
genericMockAdapter.keystoreCertificateAlias=demo-adapter-key
genericMockAdapter.keyPassword=demo-adapter-key
genericMockAdapter.keystoreLocation=${user.home}/ojb-certs/adapter/demo-adapter-keystore.jks
genericMockAdapter.keystorePassword=demo-adapter-keystore

#Trust configuration for SSL connections
genericMockAdapter.truststorePassword=demo-adapter-truststore
genericMockAdapter.truststoreLocation=${user.home}/ojb-certs/adapter/demo-adapter-truststore.jks

#######################################
####  Spring Security Configuration ###
#######################################
# The format used for the keystore. It could be set to JKS in case it is a JKS file
server.ssl.key-store-type=JKS
## The path to the keystore containing the certificate
server.ssl.key-store=${user.home}/ojb-certs/adapter/demo-adapter-keystore.jks
## The password used to generate the certificate
server.ssl.key-store-password=demo-adapter-keystore
## The alias mapped to the certificate
server.ssl.key-password=demo-adapter-key

logging.level.org.ojbc=debug

