<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:aqrequest="http://ojbc.org/IEPD/Exchange/ArrestQueryRequest/1.0" xmlns:tns="http://ojbc.org/Services/WSDL/ArrestQueryRequestService/1.0" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" targetNamespace="http://ojbc.org/Services/WSDL/ArrestQueryRequestService/1.0">
	<wsdl:import namespace="http://ojbc.org/PolicyAssertions/WSDL/GFIPM_SecurityPolicy/1.0/" location="../../../../policy-assertions/GFIPMSystemToSystem.wsdl"/>
	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://ojbc.org/IEPD/Exchange/ArrestQueryRequest/1.0" schemaLocation="../../artifacts/service_model/information_model/Arrest_Query_Request_IEPD/xsd/arrest_query_request_schema.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="ArrestQueryRequest">
		<wsdl:part name="ArrestQueryRequest" element="aqrequest:ArrestQueryRequest"/>
	</wsdl:message>
	<wsdl:portType name="Arrest-Query-Request-Service">
		<wsdl:operation name="SubmitArrestQueryRequest">
			<wsdl:input name="ArrestQueryRequest" message="tns:ArrestQueryRequest"/>
		</wsdl:operation>
	</wsdl:portType>
	<!-- Secure, GFIPM-conforming binding -->
	<wsdl:binding name="Arrest-Query-Request-Secure-ServiceSOAPBinding" type="tns:Arrest-Query-Request-Service">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsp:PolicyReference URI="#GFIPMSystemToSystem"/>
		<wsdl:operation name="SubmitArrestQueryRequest">
			<soap:operation soapAction="http://ojbc.org/Services/WSDL/ArrestQueryRequestService/1.0/SubmitArrestQueryRequest" style="document"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="Arrest-Query-Request-ServiceService">
		<wsdl:port name="Arrest-Query-Request-Secure-Service" binding="tns:Arrest-Query-Request-Secure-ServiceSOAPBinding">
			<soap:address location="http://localhost"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
