<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!--

    Unless explicitly acquired and licensed from Licensor under another license, the contents of
    this file are subject to the Reciprocal Public License ("RPL") Version 1.5, or subsequent
    versions as allowed by the RPL, and You may not copy or use this file in either source code
    or executable form, except in compliance with the terms and conditions of the RPL

    All software distributed under the RPL is provided strictly on an "AS IS" basis, WITHOUT
    WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED, AND LICENSOR HEREBY DISCLAIMS ALL SUCH
    WARRANTIES, INCLUDING WITHOUT LIMITATION, ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
    PARTICULAR PURPOSE, QUIET ENJOYMENT, OR NON-INFRINGEMENT. See the RPL for specific language
    governing rights and limitations under the RPL.

    http://opensource.org/licenses/RPL-1.5

    Copyright 2012-2015 Open Justice Broker Consortium

-->
<wsdl:definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:tns="http://ojbc.org/PolicyAssertions/WSDL/GFIPM_SecurityPolicy/1.0/" 
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy"
	xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
	xmlns:sp="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702"
	xmlns:sp13="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200802"
	xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" 
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:wsrm="http://schemas.xmlsoap.org/ws/2005/02/rm/policy" 
	name="GFIPM_System_To_System_Security_Policy" 
	targetNamespace="http://ojbc.org/PolicyAssertions/WSDL/GFIPM_SecurityPolicy/1.0/">
	<wsp:Policy wsu:Id="GFIPMSystemToSystem" Name="GFIPMSystemToSystem">
		<wsp:ExactlyOne>
			<wsp:All>
				<!-- Require WS-Addressing -->
				<wsaw:UsingAddressing wsp:Optional="false" />
				<!-- Require PKI for message protection -->
				<sp:AsymmetricBinding>
					<wsp:Policy>
						<!-- Specifies that an X509 token must ALWAYS be used to sign the message sent to the service-->
						<sp:InitiatorToken>
							<wsp:Policy>
								<sp:X509Token
									sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
									<wsp:Policy>
										<sp:RequireIssuerSerialReference />
										<sp:WssX509V3Token10 />
									</wsp:Policy>
								</sp:X509Token>
							</wsp:Policy>
						</sp:InitiatorToken>
						<sp:RecipientToken>
							<wsp:Policy>
								<sp:X509Token
									sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/Never">
									<wsp:Policy>
										<sp:RequireIssuerSerialReference />
										<sp:WssX509V3Token10 />
									</wsp:Policy>
								</sp:X509Token>
							</wsp:Policy>
						</sp:RecipientToken>
<!-- 						Security policy policy elements can occur in any order in the header -->
						<sp:Layout>
							<wsp:Policy>
								<sp:Lax />
							</wsp:Policy>
						</sp:Layout>
						<!-- A timestamp must always be in the header -->
						<sp:IncludeTimestamp />
						<!-- sign SOAP header and body-->
						<sp:OnlySignEntireHeadersAndBody />
						<!-- Specifies the signing algorithm -->
						<sp:AlgorithmSuite signatureAlgorithm="SHA256withRSA">
                            <wsp:Policy>
                                <wsp:ExactlyOne>
                                    <sp:Basic256Sha256 />
                                    <sp:Basic256Rsa15 />
                                </wsp:ExactlyOne>    
                            </wsp:Policy>
						</sp:AlgorithmSuite>
					</wsp:Policy>
				</sp:AsymmetricBinding>
				<!-- Specifies WS-Security options -->
				<sp:Wss11>
					<wsp:Policy>
						<!-- indicates that the initiator and recipient MUST be able to process references using the issuer and token serial number -->
						<sp:MustSupportRefIssuerSerial />
					</wsp:Policy>
				</sp:Wss11>
				<sp:SignedParts>
					<sp:Body />
					<sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
					<sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
					<sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
					<sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
					<sp:Header Name="Timestamp" Namespace="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" />
				</sp:SignedParts>
			</wsp:All>
		</wsp:ExactlyOne>
	</wsp:Policy>
	<wsp:Policy wsu:Id="rm-policy">
		<wsp:ExactlyOne>
			<wsp:All>
				<wsaw:UsingAddressing/>
				<wsrm:RMAssertion>
					<wsrm:InactivityTimeout Milliseconds="600000"/>
					<wsrm:AcknowledgementInterval Milliseconds="200"/>
				</wsrm:RMAssertion>
			</wsp:All>
		</wsp:ExactlyOne>
	</wsp:Policy>
</wsdl:definitions>
