<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:Q1="http://usdoj.gov/leisp/lexs/publishdiscover/3.1" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:tns="http://ojbc.org/Services/WSDL/ChargeRecommendationService/1.0" targetNamespace="http://ojbc.org/Services/WSDL/ChargeRecommendationService/1.0">
	<wsdl:import namespace="http://ojbc.org/PolicyAssertions/WSDL/GFIPM_SecurityPolicy/1.0/" location="../../../../policy-assertions/GFIPMSystemToSystem.wsdl"/>
	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://usdoj.gov/leisp/lexs/publishdiscover/3.1" schemaLocation="../../artifacts/service_model/information_model/Charge_Recommendation_IEPD/xsd/lexs/publish-discover/3.1/publish-discover.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="ChargeRecommendation">
		<wsdl:part name="ChargeRecommendation" element="Q1:doPublish"/>
	</wsdl:message>
	<wsdl:portType name="Charge-Recommendation-Service">
		<wsdl:operation name="SubmitChargeRecommendation">
			<wsdl:input name="ChargeRecommendation" message="tns:ChargeRecommendation"/>
		</wsdl:operation>
	</wsdl:portType>
	<!-- Secure, GFIPM-conforming binding -->
	<wsdl:binding name="Charge-Recommendation-ServiceSOAPBinding" type="tns:Charge-Recommendation-Service">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsp:PolicyReference URI="#GFIPMSystemToSystem"/>
		<wsdl:operation name="SubmitChargeRecommendation">
			<soap:operation soapAction="http://ojbc.org/Services/WSDL/ChargeRecommendationService/1.0/SubmitChargeRecommendation" style="document"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="Charge-Recommendation-ServiceService">
		<wsdl:port name="Charge-Recommendation-Service" binding="tns:Charge-Recommendation-ServiceSOAPBinding">
			<soap:address location="http://localhost"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
