<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns="http://schemas.xmlsoap.org/wsdl/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
	xmlns:dr="http://AdamsCounty.gov/IEPD/Exchange/BookingRecord_IEPD/1.0"
	xmlns:tns="http://AdamsCounty.gov/Services/WSDL/BookingUpdate/1.0"
	xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy"
	xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl"
	targetNamespace="http://AdamsCounty.gov/Services/WSDL/BookingUpdate_Service/1.0">
	<wsdl:import namespace="http://AdamsCounty.gov/PolicyAssertions/WSDL/GFIPM_SecurityPolicy/1.0/" 
	location="./GFIPMSystemToSystem.wsdl"/>
	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://AdamsCounty.gov/IEPD/Exchange/BookingRecord_IEPD/1.0"
			 schemaLocation="../../artifacts/service_model/information_model/BookingRecord_IEPD/xsd/exchange_schema.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="BookingRecord">
		<wsdl:part name="BookingRecord" element="dr:BookingRecord" />
	</wsdl:message>
	<wsdl:portType name="BookingRecord">
		<wsdl:operation name="UpdateBookingRecord">
			<wsdl:input name="BookingRecord" message="tns:BookingRecord" />
		</wsdl:operation>
	</wsdl:portType>
	<!-- Secure, GFIPM-conforming binding -->
	<wsdl:binding name="BookingUpdate-Secure-ServiceSOAPBinding" type="tns:BookingUpdate-Service">
		<soap:binding style="document"
			transport="http://schemas.xmlsoap.org/soap/http" />
		<wsp:PolicyReference URI="#GFIPMSystemToSystem" />
		<wsdl:operation name="UpdateBookingRecord">
			<soap:operation soapAction="http://AdamsCounty.gov/Services/WSDL/BookingUpdate-Service/1.0/BookingRecord"
				style="document" />
			<wsdl:input>
				<soap:body use="literal" />
			</wsdl:input>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="BookingUpdate-Service">
		<wsdl:port name="BookingUpdate-Secure-Service" binding="tns:BookingUpdate-Secure-ServiceSOAPBinding">
			<soap:address location="http://localhost" />
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>