# Open Justice Broker configuration file - incident_arrest_analytics_staging_adapter.cfg

# This file contains properties that are used by camel contexts in the OJB.
# Mostly it is used to define endpoint URLs

#####################################################
####  Analytical Data Store Persistence Adapter  ####
#####################################################

#Port number that service are hosted on
analyticsAdapter.cxflogging=true

analyticsAdapter.dataSource.driverClass=com.mysql.cj.jdbc.Driver
analyticsAdapter.dataSource.jdbcUrl=jdbc:mysql://localhost:3306/AnalyticsDataStore?useSSL=false&cachePrepStmts=true&useServerPrepStmts=true&rewriteBatchedStatements=true
analyticsAdapter.dataSource.user=root
analyticsAdapter.dataSource.password=mysqladmin
analyticsAdapter.dataSource.minPoolSize=5
analyticsAdapter.dataSource.maxPoolSize=20

# Analytics Web Service Endpoints - Adapters (Mocks or hosted at partner agencies - called by Intermediary)
analyticsAdapter.pretrialEnrollmentRequestAdapterEndpoint=/adapter/analyticalDataStorePersistenceAdapter/pretrialEnrollmentRequestService
analyticsAdapter.dispositionServiceAdapterEndpoint=/adapter/analyticalDataStorePersistenceAdapter/dispositionReportingService
incidentReportingService.incidentReportingServiceEndpoint=/adapter/analyticalDataStorePersistenceAdapter/incidentReportingService

analyticsAdapter.inputDirectory=/tmp/ojb/adapter/analytics
analyticsAdapter.luceneDirectory=/tmp/ojb/adapter/analytics/lucene
analyticsAdapter.luceneBackupDirectory=/tmp/ojb/adapter/analytics/luceneIndexBackups


################################
####  Security Configuration ###
################################

#Keystore used to sign messages
analyticsAdapter.keystoreCertificateAlias=demo-adapter-key
analyticsAdapter.keyPassword=demo-adapter-key
analyticsAdapter.keystoreLocation=${user.home}/ojb-certs/adapter/demo-adapter-keystore.jks
analyticsAdapter.keystorePassword=demo-adapter-keystore