<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="OJBSubscriptionManager" targetNamespace="http://www.ojbc.org/SubscribeNotify/SubscriptionManager"
    xmlns="http://www.ojbc.org/SubscribeNotify/SubscriptionManager" xmlns:tns="http://www.ojbc.org/SubscribeNotify/SubscriptionManager"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsnbn="http://docs.oasis-open.org/wsn/bw-2"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
        
    <wsdl:import namespace="http://docs.oasis-open.org/wsn/bw-2" 
        location="wsn/bw-2.wsdl"/>

    <wsdl:binding name="WSNSubscriptionMangerSoapBinding"  type="wsnbn:SubscriptionManager">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="Unsubscribe">
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
            <wsdl:fault  name="ResourceUnknownFault">
             	<soap:fault name="ResourceUnknownFault" use="literal" /> 
             </wsdl:fault>
	         <wsdl:fault  name="UnableToDestroySubscriptionFault">
	         	<soap:fault name="UnableToDestroySubscriptionFault" use="literal" /> 
	         </wsdl:fault> 
        </wsdl:operation>
    </wsdl:binding>    
       
    <wsdl:service name="SubscriptionManagerServiceService">
        <wsdl:port name="SubscriptionManager" binding="tns:WSNSubscriptionMangerSoapBinding">
          <soap:address location="http://localhost:18041/OJB/SubscriptionManager"/>
      </wsdl:port>
    </wsdl:service>
</wsdl:definitions>