<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns="http://schemas.xmlsoap.org/wsdl/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
	xmlns:disp_exc="http://ojbc.org/IEPD/Exchange/DispositionReport/1.0"
	xmlns:tns="http://ojbc.org/Services/WSDL/DispositionReportingService/1.0"
	xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy"
	xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl"
	targetNamespace="http://ojbc.org/Services/WSDL/DispositionReportingService/1.0">
	<wsdl:import namespace="http://ojbc.org/PolicyAssertions/WSDL/GFIPM_SecurityPolicy/1.0/" location="../../../../policy-assertions/GFIPMSystemToSystem.wsdl"/>
	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://ojbc.org/IEPD/Exchange/DispositionReport/1.0" schemaLocation="../../artifacts/service_model/information_model/Disposition_Report_IEPD/xsd/exchange_schema.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="DispositionReport">
		<wsdl:part name="DispositionReport" element="disp_exc:DispositionReport" />
	</wsdl:message>
	<wsdl:portType name="Disposition-Reporting-Service">
		<wsdl:operation name="ReportDisposition">
			<wsdl:input name="DispositionReport" message="tns:DispositionReport" />
		</wsdl:operation>
	</wsdl:portType>
	<!-- Secure, GFIPM-conforming binding -->
	<wsdl:binding name="Disposition-Reporting-Secure-ServiceSOAPBinding" type="tns:Disposition-Reporting-Service">
		<soap:binding style="document"
			transport="http://schemas.xmlsoap.org/soap/http" />
		<wsp:PolicyReference URI="#GFIPMSystemToSystem" />
		<wsdl:operation name="ReportDisposition">
			<soap:operation soapAction="http://ojbc.org/Services/WSDL/DispositionReportingService/1.0/ReportDisposition"
				style="document" />
			<wsdl:input>
				<soap:body use="literal" />
			</wsdl:input>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="Disposition-Reporting-ServiceService">
		<wsdl:port name="Disposition-Reporting-Secure-Service" binding="tns:Disposition-Reporting-Secure-ServiceSOAPBinding">
			<soap:address location="http://localhost" />
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>