personQuery.identificationModification.dbAuditLog=true

#########################################################
####  Identification Modification Results Endpoints  ####
#########################################################

identificationModification.federatedQueryTimeout=10000
identificationModification.cxflogging=true

# Identification Results Modification Request Endpoint - OJB Intermediary (called by query application)
identificationModification.identificationResultsModificationRequestServiceEndpoint=/intermediary/IdentificationResultsModificationRequestService

# Identification Results Modification Request Endpoint - Adapters (Mocks or hosted at partner agencies - called by Intermediary)
identificationModification.identificationResultsModificationRequestServiceAdapterEndpoint=https://localhost:8443/OJB/adapter/IdentificationResultsModificationRequestService

# Identification Results Modification Results Endpoint - OJB Intermediary (callback, called by Adapters)
identificationModification.identificationResultsModificationResponseServiceEndpoint=/intermediary/IdentificationResultsModificationResultsService

# Identification Results Modification Results Endpoint - (adapter, typically a web portal)
identificationModification.presentIdentificationResultsModificationResponseServiceEndpoint=https://localhost:18311/OJB/WebApp/PresentIdentificationResultsModificationResultService

#Keystore used to sign messages
identificationModification.keystoreCertificateAlias=demo-intermediary-key
identificationModification.keyPassword=demo-intermediary-key
identificationModification.keystoreLocation=${user.home}/ojb-certs/intermediary/demo-intermediary-keystore.jks
identificationModification.keystorePassword=demo-intermediary-keystore

#Trust configuration for SSL connections
identificationModification.truststorePassword=demo-intermediary-truststore
identificationModification.truststoreLocation=${user.home}/ojb-certs/intermediary/demo-intermediary-truststore.jks